### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by code-a-cola** [infusionsoft/infusionsoft-sdk-nodejs#2]
When running the command 'npm install infusionsoft_rest_api --save' I am receiving a 404 error message that it cannot find the latest package. Error message is below.

--------------------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'infusionsoft_rest_api',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v9.6.1
4 verbose npm-session 44ed5cea82a2b821
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/infusionsoft_rest_api 662ms
8 silly fetchPackageMetaData error for infusionsoft_rest_api@latest 404 Not Found: infusionsoft_rest_api@latest
9 verbose stack Error: 404 Not Found: infusionsoft_rest_api@latest
9 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:757:18)
9 verbose stack     at tryOnImmediate (timers.js:718:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:698:5)
10 verbose cwd /media/shane/STORAGE/node/users-api
11 verbose Linux 4.13.0-36-generic
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "infusionsoft_rest_api" "--save"
13 verbose node v9.6.1
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: infusionsoft_rest_api@latest
17 verbose exit [ 1, true ]

**Comment by karimotiva** [comment]
For some reason they changed it from `infusionsoft_rest_api` to `infusionsoft-sdk`so you'll have to npm -i that instead, I was able to get it to download and install successfully though there is one low severity security issue and a depreciated version of Babel.
[Source on NPM](https://www.npmjs.com/package/infusionsoft-sdk)

**Comment by fusion27** [comment]
## @karimotiva for the win, ran like a boss :fist_oncoming:

```sh
npm install infusionsoft-sdk --save
```
